### ISSUE TITLE
Merge with ESAPI?

### ISSUE THREAD

**Issue by JLLeitschuh** [pixee/java-security-toolkit#20]
It might be advantageous long-term to take a more vendor-neutral approach to the maintenance of this library and merge this library in with OWASP ESAPI?

https://owasp.org/www-project-enterprise-security-api/

Is this a route you considered? If you did and chose not to, why not?

**Comment by nahsra** [comment]
I contributed to and regularly advise with OWASP ESAPI. We actually answer this question explicitly in the `README`. I approached OpenSSF about hosting it and they were not interested (this was a bit shocking). I know you have relationships there, if you wanted to help -- I'd kill for it!

I have also considered hosting at OWASP. Before I bias your answer with an explanation -- what do you think about that?

**Comment by JLLeitschuh** [comment]
> We actually answer this question explicitly in the README.

Oooh, so you did. Interesting, I suppose that this makes sense.

> I approached OpenSSF about hosting it and they were not interested (this was a bit shocking).

Tell me more? The OpenSSF is more, in my experience, focused on sweeping OSS solutions. Did you approach the OpenSSF TAC, or a different group?

> I have also considered hosting at OWASP. Before I bias your answer with an explanation -- what do you think about that?

There was a recent schism at OWASP that caused a group of projects to break off and join the OpenSSF. https://owasp.org/blog/2023/08/02/zap-core-team-leaves-owasp

Personally, if I, Jonathan Leitschuh, wanted to use these libraries in remediations I generate with OpenRewrite, or some other tools, I would feel weird integrating with another companies solution, over an OSS library. As a business person this likey inclines you away from wanting to live outside the Pixxe brand.

To-date all of the automatic remediations that I've developed I've attempted to do without adding any external dependencies at all, building the entire fix into the recipe generation. Which, naturally, results in some fairly large diffs (case in point https://github.com/openrewrite/rewrite-java-security/blob/main/src/test/java/org/openrewrite/java/security/xml/DocumentBuilderFactoryXXETest.java#L214-L283)

Also, if you were to put it under an open foundation, with open governance, it would be more likely to survive any single company, which would likely make both OSS and corporations willing to accept it into their codebases.

Putting it under the Apache Software Foundation seems likely a good solution, but their governance is HEAVY from what I've heard. But it may be worth approaching them. Apache `commons-security` would be likely accepted.

**Comment by JLLeitschuh** [comment]
> Well, this is an OSS library, but I think you really mean "an OSS library housed underneath a well-known OSS organization", which is true.

Correct! I was pretty tired when I wrote that last night, thanks for understanding what I was trying to actually communicate 😆 

This is something that Eitan and Mobb has started at OWASP: https://owasp.org/www-project-consigliere---your-sast-fixing-advisor/#

**Comment by nahsra** [comment]
That seems more like a documentation project, and I'm not sure I see any activity there or how it relates to this discussion. I think I can close this issue as we have considered merging with ESAPI and rejected the idea. However, I would love any further discussion related to other places we might go and be welcome!
